#!/bin/sh

set -e

t/sizes delta.js | sed 's/^/    /'

echo ""

(proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ] || [ "$MINIFY" = "true" ]; then
  echo "generating coverage"
  t/cover

  echo "submitting coverage to coveralls.io"
  cat coverage/lcov.info | node_modules/.bin/coveralls > /dev/null

  curl 'https://www.prettyrobots.com/travisty' | sh

  echo ""
  echo "minified"
  echo ""

  # note: do not `--lift-vars` because it ruins arity functions by eliminating
  # unused function vars.
  bak=delta.js-$(date +'%FT%T').js
  mv delta.js $bak
  cat $bak | uglifyjs > delta.js

  (proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1
fi

echo ""
